# Java
For Practice

/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/

#java

import java.util.*;
public class Main
{
	public static void main(String[] args) {
		Scanner in=new Scanner(System.in);
		String str=in.nextLine();
		String str2=in.nextLine();
		int sum=0,sum1=0;
        for(int i=0;i<str.length();i++){
            sum+=(int) str.charAt(i);
            sum1+=(int) str2.charAt(i);
        }
        sum1+=str2.charAt(str2.length()-1);
        System.out.println((char)(sum1-sum));
	}
}
